apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-project-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance-project-v1
  template:
    metadata:
      labels:
        app: insurance-project-v1
    spec:
      containers:
        - name: insurance-project-v1
          image: suvo7886/insurance-project:1.0
          ports:
            - containerPort: 8080
---           
apiVersion: v1
kind: Service
metadata:
  name: insurance-project-v1
spec:
  type: NodePort
  selector:
    app: insurance-project-v1
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
